# Site
# site:
name: "Women in Computing Society"
title: "WiCS"
description: "The official blog of the Women in Computing Society at Ashoka University."
logo: 'assets/images/wics-logo.jpg'
favicon: 'favicon1.ico'
baseurl: ''
google_analytics: 'UA-158034654-1'
disqus: 'wics-blog'
mailchimp-list: 'https://github.us4.list-manage.com/subscribe/post?u=b89092d26e086848bc0fd71de&amp;id=3d337091d4'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  deepraj:
    name: Deepraj Pandey
    display_name: Deepraj
    gravatar: 4f0ba5cd9ec13e0c103a265fc4bc231e
    email: deepraj.pandey_asp21@ashoka.edu.in
    web: https://deeprajpandey.github.io
    twitter: https://twitter.com/deeprajpandey
    description: "CS Undergrad, TV Connosieur"
  rathi:
    name: Rathi Kashi
    display_name: Rathi    
    avatar: 'assets/images/rathi.jpg'
    email: rathi.kashi_asp21@ashoka.edu.in
    web: 
    twitter: https://github.com/rathikashi
    description: "CS student @ AshokaU"
  prashanthi:
    name: Prashanthi Ramachandran
    display_name: Prashanthi R
    avatar: 'assets/images/IMG-20200208-WA0011.jpg'
    email: prashanthi.r_asp21@ashoka.edu.in
    web: 
    twitter: https://github.com/prashanthi-r/
    description: "Fresh CS Grad from AshokaU."
  niyati:
    name: Niyati Bafna
    display_name: Niyati Bafna
    avatar: 'assets/images/niyati.jpeg'
    email: niyatisanjay.bafna@alumni.ashoka.edu.in
    web: 
    twitter: https://github.com/niyatibafna
    description: "English-CS grad from Ashoka, now specialising in linguistics/CL"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
